### ISSUE TITLE
Not able to find logseq graphs in linux

### ISSUE THREAD

**Issue by bhi5hmaraj** [dom8509/logseq-exporter#8]
I am getting the following error - 

```
Running logseq-to-markdown version 0.4.1
args:  [-v -o /home/bhishma/Nextcloud/Documents/code/hugo-logseq-blog Nextcloud/logseq-blog]

node:internal/process/esm_loader:46
      internalBinding('errors').triggerUncaughtException(
                                ^
el [Error]: ENOENT: no such file or directory, scandir '/root/.logseq/graphs'
    at new el (file:///usr/local/lib/node_modules/@dom8509/logseq-to-markdown/node_modules/@logseq/nbb-logseq/lib/nbb_core.js:179:94)
    at $APP.Sm.j (file:///usr/local/lib/node_modules/@dom8509/logseq-to-markdown/node_modules/@logseq/nbb-logseq/lib/nbb_core.js:1267:319)
    at file:///usr/local/lib/node_modules/@dom8509/logseq-to-markdown/node_modules/@logseq/nbb-logseq/lib/nbb_core.js:332:310
    at Jq (file:///usr/local/lib/node_modules/@dom8509/logseq-to-markdown/node_modules/@logseq/nbb-logseq/lib/nbb_core.js:332:319)
    at file:///usr/local/lib/node_modules/@dom8509/logseq-to-markdown/node_modules/@logseq/nbb-logseq/lib/nbb_core.js:562:45
    at Q (file:///usr/local/lib/node_modules/@dom8509/logseq-to-markdown/node_modules/@logseq/nbb-logseq/lib/nbb_core.js:308:469)
    at file:///usr/local/lib/node_modules/@dom8509/logseq-to-markdown/node_modules/@logseq/nbb-logseq/lib/nbb_core.js:562:321
    at Q (file:///usr/local/lib/node_modules/@dom8509/logseq-to-markdown/node_modules/@logseq/nbb-logseq/lib/nbb_core.js:308:469)
    at file:///usr/local/lib/node_modules/@dom8509/logseq-to-markdown/node_modules/@logseq/nbb-logseq/lib/nbb_core.js:562:321
    at Q (file:///usr/local/lib/node_modules/@dom8509/logseq-to-markdown/node_modules/@logseq/nbb-logseq/lib/nbb_core.js:308:469) {
  data: {
    K: null,
    O: 6,
    H: [
      {
        Nc: null,
        name: 'type',
        S: 'type',
        Vc: 1174270348,
        I: 2153775105,
        M: 4096
      },
      {
        Nc: 'sci',
        name: 'error',
        S: 'sci/error',
        Vc: -979082803,
        I: 2153775105,
        M: 4096
      },
      {
        Nc: null,
        name: 'line',
        S: 'line',
        Vc: 212345235,
        I: 2153775105,
        M: 4096
      },
      14,
      {
        Nc: null,
        name: 'column',
        S: 'column',
        Vc: 2078222095,
        I: 2153775105,
        M: 4096
      },
      10,
      {
        Nc: null,
        name: 'message',
        S: 'message',
        Vc: -406056002,
        I: 2153775105,
        M: 4096
      },
      "ENOENT: no such file or directory, scandir '/root/.logseq/graphs'",
      {
        Nc: 'sci.impl',
        name: 'callstack',
        S: 'sci.impl/callstack',
        Vc: -1621010557,
        I: 2153775105,
        M: 4096
      },
      Hh {
        state: {
          K: null,
          first: {
            K: null,
            O: 5,
            H: [Array],
            D: null,
            I: 16647951,
            M: 139268
          },
          '$b': {
            K: null,
            first: [Object],
            '$b': [Object],
            count: 8,
            D: null,
            I: 65937646,
            M: 8192
          },
          count: 9,
          D: null,
          I: 65937646,
          M: 8192
        },
        I: 32768,
        M: 0
      },
      {
        Nc: null,
        name: 'file',
        S: 'file',
        Vc: -1269645878,
        I: 2153775105,
        M: 4096
      },
      '/usr/local/lib/node_modules/@dom8509/logseq-to-markdown/src/logseq_to_markdown/graph.cljs'
    ],
    D: null,
    I: 16647951,
    M: 139268
  },
  cause: Error: ENOENT: no such file or directory, scandir '/root/.logseq/graphs'
      at Module.readdirSync (node:fs:1543:3)
      at Zfa (file:///usr/local/lib/node_modules/@dom8509/logseq-to-markdown/node_modules/@logseq/nbb-logseq/lib/nbb_core.js:337:230)
      at file:///usr/local/lib/node_modules/@dom8509/logseq-to-markdown/node_modules/@logseq/nbb-logseq/lib/nbb_core.js:600:447
      at Q (file:///usr/local/lib/node_modules/@dom8509/logseq-to-markdown/node_modules/@logseq/nbb-logseq/lib/nbb_core.js:308:469)
      at file:///usr/local/lib/node_modules/@dom8509/logseq-to-markdown/node_modules/@logseq/nbb-logseq/lib/nbb_core.js:421:113
      at file:///usr/local/lib/node_modules/@dom8509/logseq-to-markdown/node_modules/@logseq/nbb-logseq/lib/nbb_core.js:561:498
      at Q (file:///usr/local/lib/node_modules/@dom8509/logseq-to-markdown/node_modules/@logseq/nbb-logseq/lib/nbb_core.js:308:469)
      at file:///usr/local/lib/node_modules/@dom8509/logseq-to-markdown/node_modules/@logseq/nbb-logseq/lib/nbb_core.js:562:321
      at Q (file:///usr/local/lib/node_modules/@dom8509/logseq-to-markdown/node_modules/@logseq/nbb-logseq/lib/nbb_core.js:308:469)
      at file:///usr/local/lib/node_modules/@dom8509/logseq-to-markdown/node_modules/@logseq/nbb-logseq/lib/nbb_core.js:562:321 {
    errno: -2,
    syscall: 'scandir',
    code: 'ENOENT',
    path: '/root/.logseq/graphs'
  },
  description: undefined,
  number: undefined,
  fileName: undefined,
  lineNumber: undefined,
  columnNumber: undefined
}

Node.js v20.5.1
```
Looks like I would have to modify this line, to set the right path

https://github.com/dom8509/logseq-to-markdown/blob/06c9f44bd74ae2f624b7add32c50afc4348e2fa2/src/logseq_to_markdown/graph.cljs#L13

**Comment by dom8509** [comment]
@bhi5hmaraj Hi, can you tell me to what path you changed it?

**Comment by vehka** [comment]
Works for me on Ubuntu 22.04, so perhaps not a Linux issue after all?

**Comment by dom8509** [comment]
I will close this topic as it seems to be a system setup issue
